name: MIDI2Sniffer
options:
  bundleIdPrefix: com.hakaru
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  MIDI2SnifferPackage:
    path: MIDI2SnifferPackage

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: K38MBRNKAT
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  MIDI2Sniffer:
    type: application
    platform: macOS
    sources:
      - path: MIDI2Sniffer
    dependencies:
      - package: MIDI2SnifferPackage
        product: MIDI2SnifferKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hakaru.MIDI2Sniffer
        PRODUCT_NAME: MIDI2Sniffer
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "0.1.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_ENTITLEMENTS: Config/MIDI2Sniffer.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: "MIDI2Sniffer"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

schemes:
  MIDI2Sniffer:
    build:
      targets:
        MIDI2Sniffer: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
